### ISSUE TITLE
Activity + Question Uploding delay

### ISSUE THREAD

**Issue by shivd04uwedu** [ngand000/nicebreakers#44]
When uploading an Activity or Question the data does push eventually. But, for some time the new upload shows up on your local instance as if it has been pushed to the database when in reality it is only in your local instance of the database. On the backend AWS Amplify uses synchronization to eventually push your data to persistent database, but until then other users cannot see your upload on their instances. Looking into ways to force a synchronization using API calls.

**Comment by mmontelaro** [comment]
When I do it on my end, it works. Something must be up with Shivank's Amplify

**Comment by shivd04uwedu** [comment]
Update: I can see other people's updates in live time, but my updates do not push in live time. Need to do more testing on my local instance to isolate issue.

**Comment by shivd04uwedu** [comment]
I think the issue is resolved, when I upload activites/questions they now show up in the amplify database in real-time. The issue had to do with the fact that the query function was async, but the function that called it as a helper wasn't, therefore the return value didn't detect a syncronous datapush promise return and just moved on from that line.
